### PR TITLE
Reformat catalog

### PR DESCRIPTION
**Pull request by dhimmel**

### CODE REVIEW

**Comment by dhimmel** [comment]
As of https://github.com/manubot/catalog/pull/2/commits/3ea04677eaa577072af441284d8c6712b45f20e2, output is like:

image

**Comment by dhimmel** [comment]
As of https://github.com/manubot/catalog/pull/2/commits/01484ef42220f769f1f2af669f8fb438bde50b3b, output is like

image

**Comment by dhimmel** [comment]
As of https://github.com/manubot/catalog/commit/fe7b6ec79f75389b69ab57c9e2d752872dbeccd6

image

@vincerubinetti does that look good?

**Comment by agitter** [comment]
@dhimmel some of these `process-catalog.py` functions might be helpful for others who are using Manubot programmatically. For instance, they could help with https://github.com/manubot/rootstock/issues/223 and the Kipoi use case.

Once those functions are stable, do you think they could be useful additions as util functions in the `manubot` package?

**Comment by dhimmel** [comment]
> some of these process-catalog.py functions might be helpful for others who are using Manubot programmatically.

Good point @agitter. Specifically, the functions extracting processed variables from CSL JSON Items:

https://github.com/manubot/catalog/blob/2ec22ab2488e0019fbf346b1a084f030b9fe5be8/process-catalog.py#L20-L114

Initially, I was hoping to do this in CSL, but that seemed too complicated. So I made some quick and dirty python functions that are rather opinionated. It would not be hard to port them to Manubot, although their reliability is still a bit untested.

**Pull request merged**
