### PR TITLE
Added thumbnail to sPlotOpen paper

### PR DESCRIPTION
**Pull request by fmsabatini**

### CODE REVIEW

**Comment by dhimmel** [comment]
Striking thumbnail image added in https://github.com/fmsabatini/sPlotOpen_Manuscript/commit/da25e37a966da78bd2cc162ca17772e4c4b063f7!

It would actually be best to [set the thumbnail](https://github.com/manubot/rootstock/blob/defe787b0ad8a21a745cc82c3117770896caaf8b/USAGE.md#thumbnail) on your manusript rather than the catalog.

You can add the following to `metadata.yaml`:

```yaml
thumbnail: content/images/sPlotOpen_thumbnail.png
```

**Comment by agitter** [comment]
Now set in https://github.com/fmsabatini/sPlotOpen_Manuscript/commit/2d00686bd18d1c84ae1e73857bcadbbac982f502

**Comment by fmsabatini** [comment]
Thanks a lot for the advice!

**Comment by dhimmel** [comment]
Okay I will close this. Catalog will update with thumbnail next time a main branch CI runs.

**Comment by dhimmel** [comment]
Am rerunning the scheduled action, so hopefully will show up soon.

**Pull request closed without merging**
