### PR TITLE
Add comparative primate manuscript

### PR DESCRIPTION
**Pull request by agitter**
@adebali I didn't see an HTML version of your manuscript anywhere for us to link in the Manubot catalog.  Is that correct?

### CODE REVIEW

**Comment by dhimmel** [comment]
> I didn't see an HTML version of your manuscript anywhere for us to link in the Manubot catalog.

I'd have to modify the catalog compiler in order to work with missing `html_url`.

**Comment by agitter** [comment]
Should we leave this pull request open (in draft mode?) to keep track of the manuscript but avoid having to modify the compiler?

**Comment by dhimmel** [comment]
> Should we leave this pull request open (in draft mode?) to keep track of the manuscript but avoid having to modify the compiler?

good idea

**Comment by dhimmel** [comment]
Beautiful visualizations!

> thumbnail

What about using this image as the thumbnail? I will add this thumbnail_url to the catalog for now, but @adebali if you add it to your manuscript repo in a file `thumbnail.png` it might get set automatically in the HTML output metadata.

**Comment by agitter** [comment]
Thanks @adebali

**Pull request merged**
