### PR TITLE
Basic catalog processing and CI

### PR DESCRIPTION
**Pull request by dhimmel**
todo:

- [x] enable travis to deploy to github

### CODE REVIEW

**Comment by dhimmel** [comment]
Public key for Travis CI deployment to GitHub
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD3SpvOQFlo2bAwGyGJKitvUeOPkFG+rOP+ApodMLhz3/ff57BIcQTtSb9+b3idKwedvsOel8FuirSqaJEJDpnIVtet/KkaWaVOCZQ7PpvextJhmopdXO8E/oCN7MISdesrQ4/NXPN4B7a35VGSntzloIKA4b9y4fXAZIkxdSeGEMtIkmVs4O7Sb1VbuZGFRKPnGYb3NdR2m8b8TTv0cDO1SGRy9w8SE5vXg/hTXaw9P+Ab4J7igGG+6D8Hbenuc8kXtfUBeOM00KzoFx+qToR1dNUBV23Ncb1J/6s+8G35sa5Ctc+gsVCU+8rZyEA5T+QWhLCPEuhk9Kat0w0jNhR6ZQumOpJgT8doj2hP4cTE2Yds6cw72UMIemVB1c+n6mgwOpcJ+JJ8yzrU71PWtUIbPt5GHz09pTkux+cWRyihIBPoWUXYhiSyQAatdmsplnQ5LEOG8cuFcDLX2/xTkNnbfN/uK1E4qSyruOmY6CvFznU256M32lej7R/X3ihBQRTV6RN3iflnVQVjgC6A6CGdtsE0KV+gCIooz0LceO0ciBVE+jLZlnlE+Bhv1DH2swqHmnVviTOpkCqda8kijh+C//CsiGXzR1JB8HxUEAJIe6asprCdKI6Q8kkUKft/se6kgDX/Mccm2O28S0ZmXd88GanOsCeulHUwyJEfx4Vx7w== travis@travis-ci.com
```

**Comment by dhimmel** [comment]
@agitter and @vincerubinetti: I am going to merge this soon because I think that is the only way to test deployment.

The purpose of this repo is to be a place where people can add manuscripts that are made with manubot. CI extracts additional details about each catalog record and deploys the output to `output/catalog.json`. `output` gets deployed to `gh-pages`. These will then be used to populate https://manubot.org/catalog/

**Comment by agitter** [comment]
@dhimmel go ahead and merge as needed.  I can review whenever you think the catalog is ready for feedback.

**Comment by dhimmel** [comment]
@agitter see https://github.com/manubot/catalog/pull/1#issuecomment-506845671, using an environment variable rather than encrypted file could potentially make rootstock setup easier.

**Pull request merged**
