### PR TITLE
Add nf-core/eager preprint

### PR DESCRIPTION
**Pull request by jfy133**
Title: Reproducible, portable, and efficient ancient genome reconstruction with nf-core/eager

Corresponding author: @apeltzer

BioRxiv DOI: https://doi.org/10.1101/2020.06.11.145615
Manubot repo: https://github.com/apeltzer/eager2-paper/
Manubot rendered: https://apeltzer.github.io/eager2-paper

### CODE REVIEW

**Comment by jfy133** [comment]
Github != holiday @apeltzer  ;)

**Comment by dhimmel** [comment]
Beautiful manuscript! Thanks for helping keep the catalog up to date.

If you would like a thumbnail image next to your manuscript in the catalog (and also when shared on twitter), you can add a `thumbnail.png` somewhere in the repository. The catalog might take up to a week to update with the image.

**Comment by jfy133** [comment]
Thanks. 

I think the thumbnail is already there as in it's the manuscripts [metadata.yaml](https://github.com/apeltzer/eager2-paper/blob/master/content/metadata.yaml) (at the end), or does this need to be explicitly defined?

**Comment by dhimmel** [comment]
I think that should work... we'll see soon

**Comment by dhimmel** [comment]
Success

image

**Pull request merged**
