### PR TITLE
Manuscript on microCT scans & analysis of teeth

### PR DESCRIPTION
**Pull request by habi**
The manuscript itself was collaboratively written on https://www.manuscripts.io/ since I wasn't able to teach `git` to my co-authors in time, but the submitted copy was generated with `manubot`.

### CODE REVIEW

**Comment by agitter** [comment]
Thanks for adding your new manuscript.  If the thumbnail image isn't named `thumbnail.png` in your repository, it would need to be added as a line in `metadata.yaml`.  Or we can add back the `thumbnail_url` line here if that's easier.

**Comment by dhimmel** [comment]
> If the thumbnail image isn't named `thumbnail.png` in your repository, it would need to be added as a line in `metadata.yaml`.

ah good catch. Yea I don't think the repo is setting the thumbnail. You can make it any image from the repo, but must specify in metadata as @agitter describes. Best to set on manuscript rather than here so it also works for other people sharing.

**Comment by habi** [comment]
> I don't think the repo is setting the thumbnail.

I *did* set it, but didn't `git push` it 😕 
Now it should be all good: https://github.com/habi/zmk-tooth-cohort-method-manuscript/commit/16c3c7fff620746dfbdcde2c21b5423aca5be4f1

**Comment by habi** [comment]
I don't see the thumbnail in the catalog, do you have to regenerate something that it shows up there?

**Comment by dhimmel** [comment]
yeah. CI is scheduling to run once per week. But I just initiated a rerun of the CI on the merged commit for this PR. So should show up soon.

**Comment by dhimmel** [comment]
amazing thumbnail

image

**Comment by habi** [comment]
> amazing thumbnail

Thanks!
I rendered an adapted version of one of the figures in the manuscript (done with [MeVisLab](https://www.mevislab.de) especially for the thumbnail :)

**Pull request merged**
